dependencies:
    cupertino_icons: ^1.0.2
    flutter:
        sdk: flutter
description: My first flutter project which shows just a diamond pciture when the
    app opens.
dev_dependencies:
    flutter_test:
        sdk: flutter
environment:
    sdk: '>=2.12.0 <3.0.0'
flutter:
    assets:
    - images/
    uses-material-design: true
name: im_rich
publish_to: none
version: 1.0.0+1
